spring:
  datasource:
    url: jdbc:h2:mem:mqi
    username: sa
    password:
    driver-class-name: org.h2.Driver

graphql:
  servlet:
    subscriptions:
      websocket:
        path: /subscriptions
